### ISSUE TITLE
Full tablecloth extension

### ISSUE THREAD

**Issue by watterle** [vg-mjg/tablecloth-generator#13]
I assume going from just a logo to a quarter of the table shouldn't be a problem? Like the normal team tourneys

**Comment by Furitenman** [comment]
Can be done, I have the stuff more or less somewhere in the code. I'll see if I can put it together before league.

**Comment by Furitenman** [comment]
> I assume going from just a logo to a quarter of the table shouldn't be a problem? Like the normal team tourneys

I kinda have it done. I need to fix the position of the west. This should be more or less what it'll look finished.
![Majsoul_Plus_Bwg8waOfb3](https://user-images.githubusercontent.com/82289213/164893637-940b6803-0bcc-4acb-8922-72aabd0fe80b.jpg)

**Comment by watterle** [comment]
good job
