### ISSUE TITLE
Add search by name

### ISSUE THREAD

**Issue by watterle** [vg-mjg/tablecloth-generator#4]
Arguably the slowest part of making the tablecloth is checking which player is in which team. It'd be cool if you could also insert >NAMES instead of selecting the teams

**Comment by Furitenman** [comment]
Good idea, actually. I'll see to implement it

**Comment by Furitenman** [comment]
@watterle About the weeb names: Should I just write them in latin characters? I'm using the "Teams" sheet in the excel as reference for the names.

**Comment by watterle** [comment]
I don't really know...
For people who start the matches, they can copy paste the names
For the "simple" streamers, it's better to have latin characters, I guess many of them are dekinai (but at that point they wouldn't know the latin characters anyway)
Dunno, maybe keep the weeb ones? I don't have a strong opinion on this

**Comment by Furitenman** [comment]
I guess I'll try having both. I'll see how it looks in the interface and show you some results.

**Comment by Furitenman** [comment]
Well, it's finished. It took a fucking while. I hope I get rigging favours for this :^)
