### ISSUE TITLE
Save to

### ISSUE THREAD

**Issue by watterle** [vg-mjg/tablecloth-generator#6]
It'd be nice if you could input the path of the majsoul+ tablecloth mod and have the tool automatically save the picture there and overwrite the old one, instead of manually moving it

**Comment by watterle** [comment]
and keep the path saved even after closing and reopening the tool

**Comment by Furitenman** [comment]
I'll see if I can do that. Can't promise it'll be done for today.

**Comment by Furitenman** [comment]
Done, will upload the new release shortly.
